### ISSUE TITLE
Travis not installing composer dependencies

### ISSUE THREAD

**Issue by diggy** [wp-cli/scaffold-package-command#115]
I updated a package based on what's generated by `wp-cli/scaffold-package-command` and Travis tests didn't run. Because of a missing `composer install` command in install-package-tests.sh?

see https://github.com/diggy/polylang-cli/pull/63/commits/64592bff03b4f6644fc90f232cd44186a920d101 and the conversation

**Comment by danielbachhuber** [comment]
`composer install` runs in `.travis.yml`: https://github.com/wp-cli/scaffold-package-command/blob/master/.travis.yml#L44

**Comment by diggy** [comment]
Guess I'll have to ditch that funky diff tool.. thanks @danielbachhuber !

**Comment by danielbachhuber** [comment]
Yep, np. I typically run `wp scaffold package-tests <dir> --force` to bring everything up to date.
