### ISSUE TITLE
Fail build when scaffolded README is out of date

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/scaffold-package-command#116]
In our default scaffolded `bin/test.sh`, we should have some feature for failing the build when the scaffolded README is out of date.

Functionally, we'd test this by running `wp package install wp-cli/scaffold-package-command && wp scaffold package-readme ./ --force`, and then erring if any README changes were detected.

However, we'll want to be respectful of packages that only use `scaffold package-readme` once, so maybe this shouldn't be default behavior.

**Comment by swissspidy** [comment]
Is this still relevant now that we have scheduled GitHub Actions workflows that automatically update the readme?

**Comment by danielbachhuber** [comment]
Yep, we can `wontfix` this one.
