### ISSUE TITLE
Error: 'package' is not a registered subcommand of 'scaffold'

### ISSUE THREAD

**Issue by mschadegg** [wp-cli/scaffold-package-command#118]
Hi

When trying to scaffold a new package, I get the following error:
`Error: 'package' is not a registered subcommand of 'scaffold'. See 'wp help scaffold'.`

I use WP-CLI 1.2.1
And have just installed and updated the package today.

Am I missing something?

**Comment by danielbachhuber** [comment]
> And have just installed and updated the package today.

Can you try re-installing the package, and sharing the output of the installation process?

**Comment by mschadegg** [comment]
```
D:\projects\wp-project>wp package install wp-cli/scaffold-package-command

Installing package wp-cli/scaffold-package-command (dev-master)
Updating C:\Users\Martin/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Dependency resolution completed in 0.258 seconds
Analyzed 3984 packages to resolve dependencies
Analyzed 144632 rules to resolve dependencies
Package operations: 1 install, 0 updates, 0 removals
Installs: wp-cli/scaffold-package-command:dev-master a8166ed
 - Installing wp-cli/scaffold-package-command (dev-master a8166ed)
Writing lock file
Generating autoload files
---
Success: Package installed.
```

**Comment by danielbachhuber** [comment]
@mschadegg Thanks for the additional details.

WP-CLI provides limited support for Windows users. If you can track down the issue, we'd be happy to look at a pull request with the fix. Otherwise, we can't really help you debug further.

**Comment by mschadegg** [comment]
Sad WP-CLI turns down Windows users - it really limits the use cases. But I understand it is hard to support Windows.

I have downloaded the latest alpha from github, because I wantet to track down the issue, but it seems to work with the latest alpha? I don't know if it is beacuase it has not been packed to a phar file, is installed in another directory or the problem have been solved.

**Comment by danielbachhuber** [comment]
> it seems to work with the latest alpha? I don't know if it is beacuase it has not been packed to a phar file, is installed in another directory or the problem have been solved.

It's hard to say, but this might help https://github.com/wp-cli/wp-cli/issues/4145#issuecomment-307440118
