### ISSUE TITLE
Link to code review guidelines from PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/scaffold-package-command#132]
After https://github.com/wp-cli/handbook/issues/49 lands, we should link to it from the PULL_REQUEST_TEMPLATE

**Comment by danielbachhuber** [comment]
The code review guidelines are here: https://make.wordpress.org/cli/handbook/code-review/

The scaffold template itself is here: https://github.com/wp-cli/scaffold-package-command/blob/master/.github/PULL_REQUEST_TEMPLATE

**Comment by Mte90** [comment]
I can work on this one in the next days :-)
