### ISSUE TITLE
Add TOC section for packages with n+ (sub)commands?

### ISSUE THREAD

**Issue by diggy** [wp-cli/scaffold-package-command#141]
For packages with a lot of (sub)commands, it could be useful to have a concise TOC section (table of contents), cf. e.g. the readme of https://git.io/v5THM

**Comment by danielbachhuber** [comment]
@diggy It's not super clear what you're referring to in that repo. Can you share a screenshot?

**Comment by diggy** [comment]
@danielbachhuber packages with a lot of (sub)commands have a rather extensive readme, making it nearly impossible to inspect package features at a glance (think end user); hence my proposal to insert a TOC section (before Using) to give a quick overview, maybe if the n° of commands hits a certain limit

**Comment by danielbachhuber** [comment]
> packages with a lot of (sub)commands have a rather extensive readme, making it nearly impossible to inspect package features at a glance (think end user);

Oh, I see. Yes, I agree with this.

> hence my proposal to insert a TOC section (before Using) to give a quick overview, maybe if the n° of commands hits a certain limit

👍 From me.

**Comment by swissspidy** [comment]
FWIW, GitHub already shows a table of contents:

<img width="925" alt="Screenshot 2024-02-28 at 10 37 15" src="https://github.com/wp-cli/scaffold-package-command/assets/841956/616ef0bb-2d8b-4fe0-9ddd-b04a1ba56268">

Related: #227

**Comment by danielbachhuber** [comment]
@swissspidy Hm, do you suggest wontfix then?

@ernilambar What do you think?

**Comment by ernilambar** [comment]
@danielbachhuber I am leaning towards wontfix.

**Comment by swissspidy** [comment]
Same
