### ISSUE TITLE
`wp scaffold package-tests . --force` will break test files

### ISSUE THREAD

**Issue by miya0001** [wp-cli/scaffold-package-command#149]
Feature files were broken after I ran `wp scaffold package-tests . --force` like following.
https://gist.github.com/miya0001/d17a036a2a82a86f293b459f4d7868d9

Also, `a WP install` is not working.
I guess `FeatureContext::copy_dir()` isn't working as expected.

![](https://www.evernote.com/l/ABWdRnXiLjZGnIsYWIP-s7dQy4YeQwD70GQB/image.png)

**Comment by miya0001** [comment]
@wp-cli/committers 

Hmm, I don't have any idea. 😓 
Are there any mistake?

**Comment by miya0001** [comment]
Ah, we can reproduce this problem with the nightly version of WP-CLI.

**Comment by danielbachhuber** [comment]
Did you mean to run `wp scaffold package-tests ./ --force` ?

**Comment by miya0001** [comment]
@danielbachhuber 

Yes I tried `wp scaffold package-tests ./ --force` too.

**Comment by danielbachhuber** [comment]
Huh. I just tried locally and it worked fine for me: https://github.com/wp-cli/scaffold-package-command/pull/150

**Comment by miya0001** [comment]
I have same problem on the ubuntu with fresh install.
I will look into tomorrow.

**Comment by danielbachhuber** [comment]
Oh. I see what's going on. https://github.com/wp-cli/wp-cli/pull/4391 is stripping Behat comments that it shouldn't be.

**Comment by gitlost** [comment]
Ah the `@AfterSuite` etc tags in `FeatureContext`?

**Comment by danielbachhuber** [comment]
@gitlost Yep. Creating a PR now.
