### ISSUE TITLE
Update to use CircleCI version 2.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/scaffold-package-command#169]
See https://github.com/wp-cli/scaffold-command/pull/115

Should update to use CircleCI Version 2.

**Comment by danielbachhuber** [comment]
This will need to happen sooner, because [CircleCI 1.0 is sunsetting](https://circleci.com/blog/sunsetting-1-0/).

**Comment by schlessera** [comment]
Oh, this was already completed (the above PR is merged), we just didn't close off the corresponding issue.

**Comment by danielbachhuber** [comment]
@schlessera This repo still looks like v1: https://github.com/wp-cli/scaffold-package-command/blob/master/circle.yml

I think you're referring to the other.

**Comment by schlessera** [comment]
Ah, nevermind, I misread. This is for the **scaffold package** command.
