### ISSUE TITLE
CircleCi & Travis tests aren't running

### ISSUE THREAD

**Issue by Lewiscowles1986** [wp-cli/scaffold-package-command#190]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Travis / CircleCi do not seem to work, yet they form a blocking part of the repo

**Describe how other contributors can replicate this bug**

1. Create a PR (anything will do, but take #189 as example
2. Submit, having changed no existing files and adding no PHP or feature files
3. Observe failure and not running.

**Describe what you would expect as the correct outcome**

Runners that are required pass, or are fixed or removed.

**Let us know what environment you are running this on**

N/A

**Provide a possible solution**

Either Circle & Travis complete, and are fixed / confirmed should be fixed, or they get removed / downgraded?

I'm open to other suggestions. I Have two Ideas for PR's from this.

I'm not wed to any ideas. So if there are alternatives that help anyone looking to contribute, I think that's fine.

**Provide additional context/Screenshots**

I've not read the failures. I Just thought I'd pick up an issue from 2017, get it over-the-line and noticed it's not my PR, but both active PR's

**Comment by danielbachhuber** [comment]
CircleCI is fixed with https://github.com/wp-cli/scaffold-package-command/pull/203

I think we should remove support for Travis CI, given they don't have an open source plan.

@wp-cli/committers Second opinion on removing Travis CI?

**Comment by swissspidy** [comment]
Makes sense to me 👍

**Comment by Sidsector9** [comment]
LGTM 👍

**Comment by slaFFik** [comment]
CircleCI tests can't connect to DB with this error:
```
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
Waiting for MySQL...
```
So something is off in the configuration. I wasn't able to fix it now.
Apparently, the fix in #203 no longer works.

**Comment by Lewiscowles1986** [comment]
@slaFFik looks like the images have not been updated in years https://hub.docker.com/r/circleci/mariadb/tags

Also: The error message I see in logs is [1](https://app.circleci.com/pipelines/github/wp-cli/scaffold-package-command/130/workflows/6f45360b-0f4e-4a89-8e57-01fa93961a72/jobs/426) [2](https://app.circleci.com/pipelines/github/wp-cli/scaffold-package-command/135/workflows/e08290cd-2718-4169-bb6e-8692fd42fb20/jobs/431)
> E: Package 'mariadb-client-10.6' has no installation candidate


https://circleci.com/developer/images/image/cimg/mariadb points to a better target image and I see an error from ubuntu with a suggestion

> Package mariadb-client-10.6 is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
>   mariadb-client
> 
> E: Package 'mariadb-client-10.6' has no installation candidate
> 
> Exited with code exit status 100

**Comment by Lewiscowles1986** [comment]
My PR is not to say don't remove CircleCI, just:
> "Hey, maybe this stable'ish pin will help mitigate?"

**Comment by Lewiscowles1986** [comment]
Btw either way, can we close out my issue and lock it when a resolution is reached. It really was not meant for this purpose (although fixing CircleCI doesn't harm anyone)
