### ISSUE TITLE
Support alternate default branches for CI badge

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/scaffold-package-command#204]
CI badge generation is currently hardcoded to `master`:

https://github.com/wp-cli/scaffold-package-command/blob/f5684be0aef1538f5208486716c1a4fced44747d/src/ScaffoldPackageCommand.php#L258-L263

This repo now uses `main`. `trunk` is also common.

**Done is:**
* There's a flag to manually specify the preferred 'main' branch for the package.

**Comment by wojsmol** [comment]
@danielbachhuber Detecting for all setups wee be hard but we can add a parameter and set default value to for example `main`.

**Comment by danielbachhuber** [comment]
@wojsmol I'm fine with skipping the "default branch detection".
