### ISSUE TITLE
Support GitHub Actions CI config

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/scaffold-package-command#217]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

When scaffolding package tests I can only add a config for Travis CI and nothing else.

I would say the majority of developers has moved on from Travis CI to using GitHub Actions.

**Describe the solution you'd like**

Support GitHub Actions as a CI provider, and perhaps even make it the default.

**Comment by slaFFik** [comment]
> When scaffolding package tests I can only add a config for Travis CI and nothing else.

Technically you can add circleci as well (with a `--circle` flag).
