### ISSUE TITLE
Introduce Featured Commands in README in scaffold package-readme

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/scaffold-package-command#227]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

For package with large number of commands and subcommands, navigating through commands is quite difficult. TOC in the beginning of readme would be very helpful.

**Describe the solution you'd like**

List the commands anchored with corresponding command.

Example: https://github.com/ernilambar/entity-command/blob/toc/README.md

**Comment by danielbachhuber** [comment]
Thanks for the suggestion!

I think listing _all_ of the commands in a TOC could be a bit much for some. However, we could allow package authors curate the most popular commands into TOC (and indicate as such).

**Comment by ernilambar** [comment]
In `extra` in `composer.json`, lets support `featured-commands` parameter:
```
    "featured-commands": [
      "database test",
      "database reset"
    ],
```

Output would be:

![Screenshot 2024-02-26 at 12 12 46 PM](https://github.com/wp-cli/scaffold-package-command/assets/2098823/5bd49d20-ba17-41f1-a715-890791f3cac0)

Example: https://github.com/ernilambar/database-command/tree/yo-toc#readme

**Comment by danielbachhuber** [comment]
Cool, I think that looks reasonably good.

**Comment by swissspidy** [comment]
FWIW, GitHub already shows a table of contents:

<img width="925" alt="Screenshot 2024-02-28 at 10 37 15" src="https://github.com/wp-cli/scaffold-package-command/assets/841956/616ef0bb-2d8b-4fe0-9ddd-b04a1ba56268">

**Comment by ernilambar** [comment]
Yah it seems there is already an issue: https://github.com/wp-cli/scaffold-package-command/issues/141

**Comment by ernilambar** [comment]
@swissspidy That GitHub thingy of readme file looks cool. I didn't know that. Nice.
This issue was started with full TOC is mind but now discussion is going around featured commands

**Comment by ernilambar** [comment]
@danielbachhuber Featured commands was sparked from the need to see all commands in a bird eye view, which GitHub kind of already provides (even though with one extra click). So I am now neutral about this now. I am ok whatever you decide.

**Comment by danielbachhuber** [comment]
Yeah, let's wontfix this. I think it's only a problem when a package has a lot of commands, which is just a few.

Package authors can easily highlight featured commands by creating a custom section part
