### ISSUE TITLE
Improve doc for scaffold package readme command

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/scaffold-package-command#231]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

```
"support": {
  "body": "https://raw.githubusercontent.com/runcommand/runcommand-theme/master/bin/readme-partials/support-open-source.md"
},
```
Similar to `body`, our code also supports `pre` and `post`. But it is not mentioned anywhere in the documentation. Are those for internal purpose only? If those are supposed to be used publicly then it is good to be mentioned in the doc.

**Comment by danielbachhuber** [comment]
We can mention them in the docs 👍
