### ISSUE TITLE
After scaffolding package is not available as local wp command.

### ISSUE THREAD

**Issue by COLABORATI** [wp-cli/scaffold-package-command#32]
As the title says. This is a little bit disappointing. 

OK, so there is something that needs to be done to make that package an actual available command in wp. But this special magic thing is not documented. Why not?

I read the README of this repo and the wp-cli commands cookbook - no hint about what could be missing. I feel like this could be very much improved by making these kind of things just work. It would be a great system if it just made it possible to scaffold a command, put my php in it, bam, ready, run via wp-cli. I mean, I do not see that I am missing anything totally obvious - sure it will have to do with php autoloader and how wp-cli uses this, but I do not want to dig into this right now. 

So, two issues here: 
- this repo should be updated to generate something that immediately appears in the users wp-cli command list - the hello-world example command should be available after scaffolding via `wp hello-world`. 
- if there is still some manual work needed to get to that result, then this should be documented.

Thanks again for your attention.

**Comment by COLABORATI** [comment]
After looking one more time into it - is it enough to put the path to the generated command file into `~./wp-cli/config.yaml`? Will this break anything? Why did this not happen with the scaffolding process? Is this a bug? Is it enough to add this one single sentence to the README ??? :
```
After the scaffold command has run, please add your newly generated comman.php file to your 
~./wp-cli/config.yml. We do not do this autmatically, just to keep you interested :)
```

(btw why is `~./wp-cli` in my top level home dir, grrml).

**Comment by danielbachhuber** [comment]
> OK, so there is something that needs to be done to make that package an actual available command in wp. But this special magic thing is not documented. Why not?

Sorry, this is a shortcoming in the documentation right now.

Ideally, the package would be available for use, without any additional steps. But we'll need to figure out https://github.com/wp-cli/wp-cli/issues/2565 first.
