### ISSUE TITLE
Inconsistent whitespace

### ISSUE THREAD

**Issue by aaemnnosttv** [wp-cli/scaffold-package-command#44]
Right now there is a bit of a conflict with whitespace:

- `composer.mustache` uses 4 spaces
- `.editorconfig` sets .json indentation to 2 spaces

This causes problems where edits to the file after it is generated use 2 spaces, where the initial content uses 4 spaces.

Seeing as `composer init` creates the `composer.json` file with 4 spaces, and the `composer.mustache` is consistent with this, it seems to make sense that the editorconfig preserves this configuration.

**Dangerous questions:**
Does it make more sense to change the editorconfig for _all_ json to 4 spaces or that only `composer.json` should use 4 spaces and json generally uses 2?  Should editorconfig set the formatting for all json at all?

**Comment by danielbachhuber** [comment]
My preference is for JSON to be 2 spaces. For those of us using tabs consistently, 2 spaces makes it more obvious what's supposed to be spaces and what's supposed to be tabs.

We can add a one-off to `.editorconfig` if Composer balks at 2 spaces though.

**Comment by aaemnnosttv** [comment]
I don't have a problem with the indentation for json, but I do think that the formatting for composer should be consistent there.

In the same vein, indentation for `.feature` files is scaffolded with 2 spaces, where it falls under the catch-all tab indentation.  How do you feel about including these files in the rule for 2 spaces?

**Comment by danielbachhuber** [comment]
> In the same vein, indentation for `.feature` files is scaffolded with 2 spaces, where it falls under the catch-all tab indentation. How do you feel about including these files in the rule for 2 spaces?

Oh yeah, we should definitely update that too. In WP-CLI proper, even.
